pico-8 cartridge // http://www.pico-8.com
version 29
__lua__
t=0
dt=0.016
kill=0
function sqr(a) return a*a end

g={8,8+128,9,9+128,10,10+128,
   11,11+128,12,12+128,13,
   13+128,14,14+128,15,15+128}
for i=1,#g do
	pal(i,g[i],1)
end

p={10,9,8}

cls()
::♥::
t+=dt

if btn(3) then t-=dt*2 end

if btn(0) then kill-=.001 end
if btn(1) then kill+=.001 end

st=sin(t)
st1=sin(t/2)
st2=sin(t/4)
cct=cos(st1/2)

for i=1,1300 do
	x,y=rnd(128)-64,rnd(128)-64

 c=0
	c=(x - 2*sin(y/(50+10*st) + t - 2*st1) - t) / 8
	  + sin((x-st*50)*(y-t*5-st*10)/10000)
			+ y*kill + cct
	
	c=p[flr(c)%3+1]
	
	c+=(x/64)+.5*(y/18)+t*2
	
	circ(x+64,y+64,1,c)
end

flip() goto ♥
__gfx__
00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
00700700000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
00077000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
00077000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
00700700000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
__label__
abqqqqqrrrrrrrbbbbbbbbbqqqqqrrrrrrbbbbbbbqqqqqrrrrrrrqbbbqrqqbqbbbbrccccrcrrrrrrrbbbbbbbbbbbccccccrrcrrcrrrrrbbbbbbbbbbbbbcccsss
qqqqqbrqrrrrrbrbbbqbbbqqqqqrqrrrrrrbbbbbqqqqqqqrrrrrrrrrbrrrbqbqbbbccccccrrrrrrrbbbbbbbbcbcccccccrrrrrcrrrrrrbbbbbbbbbsbbscbssss
aqqqqqrrrrrrbrbrbqbqbqqqqqqqrqbrrrbbbbbqbqqqqqrrrrrrrrrrrbrbbbbbbbbccccccrrrrrrrrbbbbbbcbcccccccrrrrrrrrrrrrbrrbbbbbbsbssbssbssc
qqqqqqqrrrrrrbrbbbqbbqqqqqqrqbrbbrrbbbbbqrqqqqqrqrbrrrrrrqbbbbbbbbccccccrcrrrrrrbbbbbbbbcbcccccrcrrrrrrrrrrbrbbrbbbbcbsbbsbbsccs
qqqqqqrrrrrrqbbbbbbbqqqqqqrrrrbrrbbbbbbbqrrqqqrqrqrcrbrrrbqbbbbbbccccccccccrrrrrbbbbbbbbbbccccccrccrrrrrrrbrbbbbbbbbbsbsssssscsc
qqqqqqqrrrrqrbbbbbbqbqqqqqrrrrrrrrbbbbbqqqqqqbqrrrcrcbrrqrbbbbbbbbcccccrrcrrrrrrrbbbbbbbbcbcccccccrcrrrrrbrbrbbbrbbbbsssssscsscs
qqqqqqqqrrrrrbbbbbbbqqqqqqqrrrrrrrbbbbbqqqqqbqbrrbrcbrbrrrrbbbbbbbccccccrrrrrrrrrbbbbbbbcbcbcccccrrrrrrrrrbrbbbrbrbssssssssscccc
qqqqqqqrrrrrrrbbbbqqqqqqqqqrrrrrrrbbbbbbqqbbqbrrrrbrcrrrrrbbbbrbbbbccccrrrrrrrrrbbbbbbbcbccccccccrrrrrrrrrrbbbbrrbsbsssbsssccccc
qqqqqrrrrrrrrbbbbbqqqqqqqqrqrrrbrrbbbbbbbbbbbcrrrrccrcrrrqrbbbbbbcbccccrrrrrrrbbbbbbbbcccrbccccrrrrrrrrrrbrrrbrbrbrsbcbssssssccc
qqqqqrrrrrrrrbbbbbbqqqqqqrrrrrrrrbrbbbbbbqbbbrcrrcrccrqrrrbrbbbbcccccccrrrrrrbrbbrbbbbccccccccrrrrrrrrrrbrrrrrbrbrbrrssssssssccc
qqqqqqrrrrrrbbbbbbbqqqqqqrrrrrrrbrbbbbbbqbbbbbrrcrcrcrrrrrrbbbbbccccccccrrrrrrrrbbbbbbccccccccrrrcrrrrrrrbbrcrrbsbsssssssssscscc
qqqqqrrrrrrbbbbbqbqqqqqqrqrrrrrrbbbbbbqqbbbbbbbcrcrcrrrrrbbbbbbbcccccccrcrrrrrrrbbbbbbccccbccccrrrrrrrrrrrbrrbrsbssssssssssssccc
bqqqqrrrrrrrbbbbbqbqqqqqqrqqrrrrbbbbbbqbbbbbbbcccccrcrrrrrbbbbbbbcccccccrrrrrrrrrbbbbbbcbbccccrrrrrcrrrrrrrrrrsbsrssrssssssscscc
qqqqqqrrrrrrbbbbbbqbqqqqrqqrqrrrcbbbbrrbbbbbbcbcccccrrrrrrbrbbbbbcccccccrvrrrrrrbbbbbbbbccccccrrrrcrccrrrrrrrrrsrsrrssssrsscsccc
qqqqqrqrrrrrrbbbbbbqbqqqqqrqrrrcbcbbrrrrbbbbbbccccccrrrrrrrbbbbbbccccccccrrrrrrbbbbbbbbcccccccrrrccccccrrrbrrrrrsrbsrssssccscccc
qqqqrqqrrrrrbbbbbbbbqbqqqrrrrrrccrbrrrrbqbbbbbcccccrrrrrrrrbbbbbcbccccccrrrrrrrrrbbbbbbccccccccrccccccrrrrrrrrrrcssssssssscccccc
qqqqqqrqrvrbbbbbbbqbbqqqrqrrrrccccrrrrbqbqbbbccccccrrrrrrrbrbrbbbcbccccrcrrrrrrrbbbbbbbcccccccsccccrcbrrrrrrrrrrrsssssssscsccccc
qqqqrrqrrrbbbbbbbbbqqqqrqrrrcccccrrrrbqbqbbbbbbcccccrrrrrbrbcbbbcbccccccrrrrrrrbbbbbbbcccscscscscccccrrrrrrrrrrrsssssssscscccccc
qqqrqrrrrrbbbbbbbqqqqqrqrqcccccqrrrrbrbbbbbbbbcbccccrrrrrrbbbbbbbbcccccrrrrrrrrbbbbbbbbcscscscsccccccccrrrrrrrrrssssssscsccccccc
qqqrrqbrrbrbbbbbqbqqqbrrqcccccqcrcrrrbrqbbbcbcbccccrcrrrrrrbbcbbbbbcccccrrrrrrrbbbbbbbbscscscsccccccccrcrrrrrrrsrssssssscccccccc
qqrrqrqrrrbbbbbbbqbqqqrbrbbccrcqcccrrrbrbbbbccccccccrrrrrrbrcbbbbbbbcccrcrrrrrrbbbbbbbcbscsssssccccccccrcrrrrrsrsrsssssccccccccc
rqqrqqrrrrrbbbbbqbqqqbbrbbrbccbccccrrbrbbbbbbcccccccrrrrrrrrbbbbbbbbbcrcrcrrrrrrbbbbrcbcbsssssscccccccccrrrrrrrssssssscscccccccc
qqqqrqrrrrrrbbbbbbqqbrbbbbbccccbccrrbrrrrbbbcbcccrcrcrrrrrbbbbbbbbbbcccrcrrrrrrrcbbrbrcsrssssscccccccccrrrrrrrrrrssssssssccccccc
qqqrqrrrrrrbbbbbbqbqrbrbbbrcccbcqcrrbrrrbrbbbcccrcrcrrrrrbrbbbbbbbbcccccrrcrrrrcrcbbrbsrrrssssscsrccccccrrrrrrrrrssssscsccccccrc
qrqrrrrrrrrrbbbbrbqqrrbbbbccccccccrrrrrrrbrbbcccbccrcrrrrrrrbrbbbbcbccccrcrcrcrrcbbbrrrrrrsssssscscccccccrrrrrrrssssssscccccccrc
rqrqrrrrrrrrrbbrbrbrbrbbbbbccccccccrrrrbbrbbbbcbcbccrcrrbrrrrbrbbcbcccccrccrcrccccrrbrrrrsssssssscccccccrcrrrrrrrssssssccccccccc
qrqrqrrrrbrrccbbrbrbrbbbbbbbcccccccrrrrrbrbbbbbcbccrccrrrrrrbrbbcccccccccsccrccccrcrrbrcsssssssscsscccccccrrrrrrrrsssssccccccccc
rqrqrrrrbcbccccbbrbrbrbbrbbcccccrcrcrrrbrbbbbbcbcrrccccrrrrbbbbbbcccccccscsssccccccrrrbsrsssssscsscscccccccrrrrrrrsssssscccccccc
brqqrrrbcbcbccrrrbrbrbrbbbcccccccrcrrrrrbrbbbcbcccrrcccrrrbbbrbbbcbccccssrssscccccbccrrrsrsssssssssccccrcccrrrrrrrsssssssccccccc
bbqrqrrrccbcbrrqrrbrbrbbbbccccccrcrcrrrrrbrbbcccbcccccrrrrbbrrrbbbrrcccsssrscsccccccrcrrrsrsssssssscccrcccrrrrrrrrrssssssccccrcc
bbqbrrrcrccbccbrrqrqrbbbbbbbcccrrrcrrrrrbrbbcccbbbcccccrrrrbrrrbbrrrrrsssssrsccccccrcrrrsrsssssssscccccccccrrrrrrrsssssscccccccc
bqbqbrrbccqccccqrrbrrbrbbbbbbrccrrrrrrbrrbrcbbcbbbccccccrrrbbrrbrbrrrrrssssrscccccccrcrrrssssssssscccrcccccrrrrrrrsssssssccccccc
rrqbbrbcbccbccrrrrrrbrbbbbbbbbccccrrrrrbrrbrbcbcbcbcccccrrrrbbbcbrbrrrrcssrsrsccbcrccrcrrrssssssssscccccccrcrrsrrrsssssscccccccc
rbbbrbcbccrccrbrrrrrrbbbbbbbbbcccrcrrrbrrrrbbbcbcbcccccrrrrrbbcbcbrbrrcsssscsrcccccrrcrrrrrssssssssscccccrcrrrrsrsrssssssccccscs
bbbbbbbcccrcrcrrrrrrrbbbbbbbbcccrcrrrrrrrrrbbbbbbbbcccccrrrcrcbcbrbrrrsssssscscccccccrrrrrrrsssccsssscccrcrrsrrrsrsssssscsccccsr
bbbbbbbccccrccrrrbrrrrbbbbbcbccrcrrrrrrrrrbbbbbbbbbcrcccrcbrrrcbrbrbrrssssssssscccccccrrrrrrrssscssssccccrscrrrrrsssssssscccsccc
bbbbbbrccccccccrbrbbrrbbcbcbccccccrrrrrrbrbbbccbbbbccrccsbcbrcbcbrcrsrssssssssscccccccrrrrrrrsscscsssccccccrcrrrrrsssssssscscscs
bbbbbbcbccccccrrrbbbrbbcbcbcbcccccrrrrrbrbbbbbcbbbcccccssscrcrcbrbrrrsrsssssssccccccccrrrrrrrscscsssccccccrcrrrrrrrsssssdrccssss
brbrbbbcrccccrrrrrbrcrbbcbcbcccccrrrrrbrbrcbbbbcbccccccsssccrcbbrrrrrrsssssssscccccccrcrrrssssscsssssccccrcrcrrsrrsssssddddcscss
rbbbbbbcccccccrrrbrrrbbbbbbcccccrrcrrrrbrbbcbbbbcccccrcrscccbccrrrrrrsrsssssssccccccccrrrrrrssssssssscccccccrrrrrrrrsssdddddssss
bbbbcbcccccccrrrrrrrrbbbbbbcrcccrcrcrrrrrbbbbbbbbcscccrcrcccccccrrrssrsrssssscsccccccccrrrrsrsssssssccccccccrrscrrrrsdddddddssss
bbbbccccccccccrrrrrrbbbbbbbcrccccrcrrrrrrrbbbbbbbbcssrcscrcbcccccrrrrsrsssssssccccccccrrrsrrssssssssccccccccrrcrcrrscddddddsssss
rbbbbccccccccrrrrbrbbbbbbbcbcbccrcrrrrrrrrrbbrbbbcssrsscscbcccccrrrrrrsssssssscccccccrrrrrrrrssssssccccccccccrrcrsccsddsddddssss
bbbbbbccccrcrrbrbrrbbbbbbbbccccccrrrrrrrrrbbrcrrcsccsscscccccccrrrrrrrsssssssccccccccrrrrrrrrrsssssscscccccsrrcrccscsdsddddsssss
bbbbbccccccrrrrrrrbbbbbbbcbcccccbcrrrrrrbrbrbrrcrssssrsccccbcccrrrrrrrrsssssssccccccrrrrrrrrrscsssscsccccsscscrcccccssddddddssss
bbbbccccccccrrrbrrbbbbcbbbcccccccrrrrrrrrrbrrrrrssssssssccbcbcccrrrrrrrsscsssssccccccrrrrrrrssscsssscsccscsscccccccccdddddddssss
bbbbbcrccccrrrbrrrrbbbbbbbcccccccrrrrrbcrcrbrbrrssssssssccccccrcrrrrrrrssscsssscccccccrrrrrrsssssssssscccscscrcccccccddddddsssss
bbbccccrccrrrrrrrrrbbbbbbbccccccccrrcrrccrbrbrrssssssssscccrcrcrrrrrrrrrssscsscccccccrrrrrrrrsssssssscscscssrcrcccccsdddddrssdss
bbccccccrrrrrrrrrrbrbbbbbbccccccccrcrcrrcbrbrbrsssssssssscccccrrrrrrrrrsssssscccccccrrrrrrrrrrssssdssscscssssrccccrccdddddsdssds
bbbccccccrrrrrrrrrrbbcbcbccccccccrcrccrbbrbrcrrrsssssssscccccrcrrrrrrrrssssssscccccrrrrrrrrrrrsssdsdssscssssscrccrccdcdddddsssss
bbbccccccrrrrrrrrbbbbbcbcccccsccccrccccbbrrrrrrsssssssscccccccrrrrrrrrrssssssssccrccrrrrrrrrrrssdddssssscssscccccccccdddddcsssss
cccccccccrrrrrrrbrbbbcbcbcccscsccrcccccbrbrrrrrsssssssccccccccrrrrrrrrssssssssscccccccrrrrrrrrsddddssssssssccccccccdcdcddddsssss
ccccccccrcrrrrrrrbbbbbcbbcccsscscccccccrbrrrrrsrssssssccccccccrrrrrrrrssssssssccccccccrrrrrrrrdsddssssssssssccccccdcdcdsdddsssss
bccccccccrrbrrrrrbbbbbbbcbcscsscccccccrcrrrrrrrssssrscccccccccccrrrrrsssssssscscccccccrrrcrrcdddddddssdssssssccccccdcdddddddssss
cccccccccrrrrrrrrbbbbbbcbcccsscccccccrcrrrrrrrbrssssscccccccccrccrrrrrsssssscccccccccccrccccrcddddsdsdscssssssccrcccddddddddssss
cccccccccrrrrrrrbbbbbbbscccsccscccrcrcrrrrrrrrrcsssssccccccccrcrrcrrrrrrsssscccccrccccccccrccrddddddssdssssssscccscccddddddddsss
ccccccccrrrrrrrrbbbbbrscscscsscscccrccrrrrrrrrsssssssscsccccccrcrrrrrssrrsssscsccccsccccrrccccrcdddsdsssssssscccccscccddddddssss
cccccccrcrrrrrrrbbbrrbrsccsssssccccccrcrrrrrrsrsssssssccsccccccrrrrrsrssssssssccccsssccrcrcccccdddddsdsssssssscccrcccccddcddssss
cccccccrrrrrrrbbrbrbrrbsbscssscscccccccrrrrrrrsrssssscscccccccccrrrrrsssssssssscccssscccrcccccdddddddddsssssscscccccccdcdddddsss
ccccccrrrrrrrbrbbbrrrcsbssssssscccccccrrrrrrrrrsrsssssscccccccccrrrrrrsssssssssccscscscccccccccddddddcdssssssscscccccdcdddddddds
cccccccrrrrrrrbrbrrrrrsssssssscscccccrcrrrrrrrssssssssssccccccccrrrrrrssssssdsscscssscscccccccddddddcddsssssssscccccccddddddddds
ccrccccrrrrrrrrrrrrrrsrssssssssccccccbrrrrrrrrsssssssssscccccccrrsrrrrsssssdddcssssssscsccccccddsddsdddsssssssscccccccddddddddsd
cccccccrrrcrcrrrrrrbrrsssssssssscccccccrrrrrrrrsssbssssccccccccrrrrrrrrssrsdddsssssssssccccccrcsccdddddssssssssccccccccdddddddds
cccccccrcrrcbrbbrrrrrrssssssssscccccccccrrrrrrsrssssssscccccccccrcrrrrcsrsrdddsdssssssccccccccccsdddddddssssssssccccccccccddddsd
ccccccscrcrrrbcbrrrrrrrssssssscsccccccccrrrrrrrsrssssscsccccccccrrrrrcrcsrdddsdddssssccccccccccccddddddddsssssssscccccccdcddddds
cccccssscrrrccbcrrbrrrsrssssssscccccccccrrrrrrsrssssssscccccccccrrrrrrcrcddddsdddcsscssscscccccccdddddddsssssssssscccccdcdcddddd
cccccsscrrccrccrbrrrrrrssssssssccccccccccrrrrrrssssssssscccccccrcrrrrrrcrsddddddddccssssscccccccdcdddddddsssssssscccccccdcdddddd
cccssrcccccccrrbrrbrrrrrcssssssccccccccccrrrrrrrssssssscccccccccrrrrrrcrcsddddddddsssssssscccccccddcddddsssssssssscccccccdcddddd
ccssssccccccccrrbrrrrrrrssssssssccccccrcrrrrrrrsrssssssscccccscccrrcscrcrdsdsdddddsssssssssccccccdcddddddsssssssscscccccccdcdddd
cccsssrcrrccccrcrrrrrrrssssssssccccccccrrrrrrrrrrrsssssscsccsssccrcrcccccrdddddddddsssssssccccccccdddddddssssssssscscccccccddddd
csscsrrbcccccccrcrrrrrsrssssssssccccccccrrrrrrrrrsrsssssscccssscrsrcccccccddddddddssssssssscccccccdcddddddsssssssssscccccccddddd
ssssrrscccccccccrrrrrsrssssssssscccccccccrrrrrrsrrsssssssscccsccscsrrcrccccddddscddssssrsssscccccccddddddddsssssssscscccccccdddd
ssscsscscccccccrrrrrrrssssssssssscccccccrrrrrrrrsrsssssssdcccsccsscccrcccccdddsdddddsssssssccccccccdddddddddsssssssscsccccsccdtd
cscscsscccccrcrrrrrrrrrssssssssssccccccrcsrrrrrrrrrsssssdsdcssssssscrccccccdddddddddssssssssccccccccddddddddddsssssssccccscsdtdt
scssscsscccrcrcrrrrrrrsrssssssssssccccccccrrrrrrrrsssssssdscssscssrrcrcccccdddddddddsssssssccccccccccdddddddddssssssdsscccscsdtt
rsssssscscrccccrrrrrrrrrrssssssssccccccccccrrrrrrrsddsssddddssssssscccccccccdddddddsdsssssssccccccccccddddddddsssssdsdssscssdsst
csssssssccccccccrrrrrrrrrsssssssccccccccccrrrrrrrrddddsddddddsssssrcccccccccddddddddsdssssssscccccccccdddddddsdsssssdcssssssssss
ssssssssccccccccrrrrrrrrrsssssscscccccccccrrrrrrrcsddsddddddsssssssccccccccdcddddddddsdssssssccccccccdddddddddsdsssdsdcssssscsss
sssssssccccccccccrrrrrrrrssssssscccccccccccrrrrrcrcssddddddsssssssssccccccccddddddddsdsssssssssccccccccddddddddsdsdddcdsdsscssst
sssssssccccccrccrrrrrrrrssssssssccccccccccrcrrrrrcccsddddddssssssssccccccccccddddddddssssssssscsccccccccddddddtdddddddcdscssdsss
ssssssscccccccrrrrrrrrrsssssssssccccccccsrcrrrrrrcccddddsdddssssssssccccccccccddddddddssssssssscsccccccddtddttdddddddsdcdssdssss
sssssssccccccccrrrrrrrrrsssssssssccccccscscccrrcrrcddddsdddddssssssssccccccccddddddddssssssssssscccccccctdttttddddddddsdssdsssss
sssssscsccccccrrrrrrrrrrrsssssssssccscccscccrccccrcddddddddddssssssscsccccccdcdddddddsssssssssssccccccccctdttttddddddddsdsssssss
ssssssscccccccrrrrrrrrrrrrsssscssscscsccscccccccccccdddddddddssssssrscsccccccdcdddddddsssssssssccccsccccdttttttttdddddddsdssssss
ssssssccccccccrrrrrrrrrrrsssssssssccsscccsccccccccccddddddddddssssssscscccccccdddddddddsssssssssccscsccstdttttttdtdddddddddsssss
sssssssccccccccrrrrrrrrrssssssssscscscssscscccccrcddcdddddddsrsssssscccccccccccddddsdddssssssscscscsccsssttttttttddddddddddssssd
ssssssscccccccccrrrrrrrsrssssssssscscsssscrccccccdcddddddddsdssssssscccccccccccdcddddddsdsssssssssssdcsstdtttttttddddddddddsssts
sssssscccccccccrrrrrrrsssrsssssssssccrsscsccccccccddcddddcddssssssssscccccccccccddddddsssdssssssdsscsscsdtdtttttttddddddddssssss
ssssssccccccccrrrrrrrrssssrssdssssscccscsccccsccccdcddddddddssssssssssssccccccdcddddddssssssscsdsdcssssssstdtttttddddddddsssssss
ssscscsccccccccrrrrrrsrsrsssdsdssssscccsccccsccccdcdddddddssdsssssscsssscccccdcddddddsdsssssdsssdsssssstssttttttddddddddssssssss
sscscccccccrccrcrrrrrrsrsssssdssssssscsccccccsccdcdcdddddsdssssssscscsccccccccddddddddsdsdsdsdddsssssststtsttttddddddddsssssssss
ssscccccccccccrrrrrrrrrsssdssssssdsscssscccrsccccdcdcdddddsddsssssscscscccccccdddddddddsdssddsddssssssststttttddddddddsdssssssss
sssccccccccccrrrrrrrcrddsdsddsssssssssssssrcccccccdcdcdddsddsssdsssscccccccccdcdddddddddssddsdddsssssssstttttttddddddddsssssssss
ssccccccccccrcrrrrccrcddddddsdssssssssscssccccccccsdcdcdsdssssssssssccccccccccddddttttdddddddddsdsssssssttttttdtdddddddddsssssss
sscccscccccrcrrrrcrccrdddsdsssdsssdssscscsccccccccdddccddsddssssdssccccccccccdcddtdttdddddddddddsssssssstttttdtdtdddddddssssssss
ssccccccccccrcrrrrcddrrdddssdsssssssssscscccssccccdddddddddddsssscssccscccccccddcdtddtddddddcddsdsssssstttttttdtdcdddsdsssssssst
scsccccccccccrrrcrddddddddddsdsdssssssssccccccccdcddddddddsdsssssscsssccccccccdcdttttdtdddddddsssssssssstttttttdsddddddssssssstd
cscsccccccccccccrccddrcddddddsdsdssssssccccccccccccddddddsssdssssssssccccccccdtdctttttdtdddddddssdssssssstttttdtdsddddddssssstst
scsccsccccrcccccccrccccrddddddsdsdssssscccsccsccccdddddddssssdssssssssccccscctdtttttddtdddddddsdsssssssttttttttdsdsddddssssststt
sscccccccccccccccccdccrdddddsdddddsssssscccsccsccdcdddddddsdddsssssssssccsssccttttttttdtdddddddsdssssstttttttttdddddddsssssssstt
scccccccccccccccccdddrdddddsdsddddsssrssccccscccdcdcdcdddddddsdsssscsscsdssssttttttttttdtdddddsssssssssttttttttdddddddssssssssst
scccccccccccccccccdddrdddddrsdsddssscsrcsccccccccdddcddddsddssssssccccccsssststttttttttdddcdddsssssssssttdtttttddddddsssssstssst
sccccccccccccccrccddrccddddddsssdssssscscccccccccdcdddddsdsssssssdccccscssststctctdtttddddddddssssssssstttttdtddddddsssssssststt
ssscsccsccccccrcrddddddcdddddsssssssssscccccccccdddccddddsdsssssdsdcsscssssstcsttststtdddcdddsssssssssttttttddddddsstsssssststet
sscsssscsccccscrcddddddddddsdssssssssccsccccccccdddddddddddssdsssdsdssssssssssttttsttddddddddssssssssssttttddddddddssssssssstete
scsssssscscccccrcdddddcdddsdsssdsssscsccssscccsddddccdddddsssssddsdsssssssssssttttttttddddddddssssssssssttcddsddddddsdssssstttet
sccsssssscscccccccdcdddddddssdsssssssccccscccsdcddccdcddddsssdddddsssssssssssstttttttdtddddddsdssssssssttttdtddddddsdsdsstsddtdt
sscssssssscccccccdrddddddcsdssdsssssssccsscccccdcdcccddddddsdddddddsssssssssstttttttttdtddddddssssssstttttttdtddddddsdtstsddeete
sscsssssccccccccccdcddddcddsdssssssssscsccsccccdddddcdddddddddddddddcssssscssstttttttdtdddsdssdssssststttttttddddddtsttsstseeeed
sscssscccccccccccdddddddddddsdssssssscscscccccdcddddddddddddddddddddddssssscsdstttttttdddddtddsdssssststtttttdsddddddssdsdddeede
scsssssccccccccccddddddddddddssssscssscscscccccdcdddddddtdddddddddddddsssscstststttttddddsddssdsdssstssttttttddssddtdddddtddteee
sscsssssccccccscccddddcdddddddsssssdssscscccccccdtdddtdtttddddddddddddsssvssststtttttttddddsddsdssstssstdtdtdddtddtdtsdddsddeeee
ssssssssscccccccccdcdcdddddddsdssssssssscscccccccctttdtttttddddddddddssssssssststtttttdtddsdddstsssssssstdddddtdttttsstdtddddeee
dssssssssccccccccccdcdddddddddddssssssssscscccccctttttttttdddddddddddssssssssssttttttttdtsddddtsssssssstdtdddsetttttststdeddeeee
ddssssssssccccccccdcddddddddddddsssssssssscccsccccctttttttdddtddddddsdsssssssttsttttttttddsdddsdsssssssdtttddeeedttttsdddddddeee
dssssssssscccccccdcddddddddddddsssssssssscscssscccscdttttttdtddddddddsdsssssssststttttdtdddsdsdsdssssssttttteeeeststtdtdddddeeee
ddssssssssscccccccddddddddddddsssssssssssscssssccscsttttttttsttdddddddsdsssstssstttttdtdtdddsdddssdssstttttteeeststtdddtedteetee
ddssssssssccccccccccdddddddddsdssssssssdssssssssccsctttttttttdttdddddddssssssssssttttddtsdddddddsssstttsttttetsttttdtddededteeee
dssssssssscccccccccccdddddddsdsdssssssdsdsssssssscctctdtttttdtdtddddddddssssssssssttdttsdddssddsssstsdstsdedtttttttttdddedeeeeee
dssssssssssccccccccccddddddddsddsssssssdssssssssscsctstttttttdtdddddddddssssssssstttttdtdddddsssdssstddsdedettttttttdtdddedeeede
sdssssssssccccccccccccdddddddddssssssddsdsssssssssssststttdtttdddddddddddssssssstttttdtdtdddddddsdsssddddsedttsdtttttddeddtdetee
dsssssssssscccccccccccdddcddddssssdsddddsdssssssssssssttttttttddtdddddddsdstssssstttstttddddddttdsdsdtdeedsesttddttdtdededddteed
dddssssssssccccccccccddddddddddssdsddddsdssscdssssssssstttttttttttdddddddssstssststttttddddddttdtdddtdedeeesetdttdetdeetdedtdtte
ddddssssssssccccccccccddddddddddddddddddsscsddsdsssssststtttttttdtdddddddsssssssstttttttddsttddtdtddstdeeteeetetttededeeededtttt
ddddssdsssscccccccccccdcdddddtdddddddddddssddsdsssssststsstttttdtddddddddsssssststtttttdsttdttddsddsddeeeeeetetetttedeeededteett
ddddssssssscccccccccdcddctddtttdddddddddsdsdsdsssssssstsstttttttddddsddddtsssssststtttddtdtttstsddddddedeeeeetettttedeedededeeet
dddssscssscscccccccdcdddtdtttttddddddddddsdddsdssssssststttttttttdddddddddtsssssststtdtdstdtttttdddddddedeeetedtttddedeededteeet
ddddcsssscscscccccscdcdcdtttttddsttdddddddddsdsdsssssssttttttttttddddddddddssssststtstdtdttttttttdteddedetetedddtdddddeeedettete

