pico-8 cartridge // http://www.pico-8.com
version 29
__lua__
function fflr(a,unit)
	return flr(a/unit)*unit
end

t=0
smpl=1000

for i=0,7 do
	pal(i,i+8+128,1)
end

cls()
::♥::
t+=1/30

local st16=sin(t/16)

for i=1,1200 do
	local x,y=rnd(128),rnd(128)
	local c=0
	 + (x/2-y/2) / (32 + 16*st16) 
	 + sin((y+200)/4/(x+32))/4
	 + t/3

	local diff=c-flr(c)

	c=flr(c)
	 +0.75*flr(x/64+y/16+t)

	c=c%8+8
	if diff>0.5+0.2*sin(t/8) then
		c-=8
	end
	
	circ(x,y,1,c)
end

print(smpl,0,0,0)

flip() goto ♥
__label__
oooooooooooooooooooo99999aaaqqqp9qqq9pqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqbqbbbbbbbbqbqbbbbbbbbsssbbbssssbsbssssbsssrsssssssssssssd
ooooooooooooooooooooo9999aaaqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqbbbbbbbbbbbbbbbbcbbcssssssbsssssssssbsssssssssssssssssss
ooo8ooooooooooooooopooo99aaaaqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqbbqbbbqbbcbbbccccccssssssbssssssssssssssssssssssssssss
oooooooooooooooooppopoa9a9aaaaqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqbqcqbcbccccbcccccccscsssccssssssssssssssssssssssssssss
ooooooooooooooopppppopoaoaaaaaaaqqqaaqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqbqcqccqcbccccccccccscscsscsssscssssssssssssssssssssssss
ooo8o8oo8oppopppppppppaopa9aaaaqaqaaqaqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqrqqqqbqccqcccccccccccccccccssscsssscsssssssssssssssscssssss
p8888p889p9pppppppppppppapaaaaaaqaqqaqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqrqrrrrqrrcccqcccqccrcbccccccssscsssssssssssssscsssssssssssss
opp8p9p989p9p8pppppppppapaaaaaaaaqqqqqaqqqqqqqqqqqqqqqqqqqqqqrqqqqqrqrrrrqrrcrccccccccccrrcccccccscscsssscssssssssscssssssssssst
pp8p9p99999p9pppppppppppapaaaaaaaaqqaaqaqqqqqqqqqqqqqqrqqqqrrqrrqqrrrqrrrrrrrrcrcrcccccrccccccccccccsssccssssssssscstssssstsstts
pop999999999pppppppppppppaaaaaaaaaaqaqaqqqqqqqqqqqqqqrqrqrrrrrrrrrrrrrqrqrrrrrrcrcrcccrcrcccccccccccssscccssssssssststssststtttt
op989999999899pppppppppppppaoaaaaaqaqaqqqqqqqqrqqqqqrqrrrrrrrrrrrrrrrqrrrrrrrrrrrrcrcrcrccccccccccccssscsssssssssststsssssttsttt
p8p999999899999ppppppppppppppaaaaaaqaqqqqqqqqrqrqqqrrrrrrrrrrrrrrrqrrrrrrrrqrrrrrrrcrcrcccccrccrcccscscscsssssssststtsssststtttt
pp899999v999999pppppppppppppppaaaaaaqaqqarqrqqrqqrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrcccrccccrrccccccscscstssctssstttctsctststttt
p9p99999999999pppppppppppppppppaaaaaaqaararqrrqrqrrrrrrrrrrrrrrrrrarrrrrrrrrrrrrrrrrcrccccccrcccccccddcttttctttctsttttttttststtt
pp9999999999999pppppppppppppppaaaabaaaabararaarqrqrrrrrrrrrrrrrarrrrrrrrrrrrrrrrrrrrrcrcrcccrccccccdddddttcctttttttttttttttttttt
ppp9999999999999pppppppppppppqpaabpbabbabbbrbaarqrrrrrrrqrrrrrrrrrrrrrrrrrrrrrrrrrrrrrcrccdcccccrdccddcddcdccttttttttttttttttttt
pp99999999999999pppppppqppppqpqpbpbababbbabbrbabrrrbrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrcrcrdcdccccddcdddddddcdttttttdtttcttttttttt
p9999999999999999pppppqpqppqqqpqpbaabbbbabbrrbrrrrbrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrscrrrdcdrcddddddddddddddtttddtttttdtttrtttt
99999999999o99999qqppqpqpqqqqqqpbpbbbbbabbbrbrrrrrrrbrrrrrrrrrrrrrrrrrrrrrrrrsrrrrsrsrsrsssdssssddrcdddddddddtttttttttttdtrttdtt
9999999999o9a99aqqqqqpqpqppqqqqbqbbbbbbbbbbbrbrrrabrrrrrrrrrrrrrrrrrrrrrrrrrsrsrrsrsrssssssssssddddddrdsdddddttttttttttttdtttttt
99999999oo9a9aa9aqqqqqpqpqqqqqqqbqqbbbbbbbbbbbrbbbrrrrrrrrrrrrrrrrrrrrrsrrsrrsrrsssrsrsssssssssddddddddrdsddddtttttttttttttttttt
999999999a9aaa9aaaaqqqqpqqqqqqqqqqqbbbbbbbbbbbbbrrrrrrrrrrrrrrbrrrsrrrsrssrsrsssssssrsssssssssssdsddsddddddddddtdtdstttttttttttd
999a999aaaa9aoaaaaaaqqpqqqqqqqqqqqqbbbbbbbbbbbbrrrrrrrrrrrrrrrrsrsrsrrssrsssssssrssssssssssrsssssdddddddddddddddtdsdtttttttttttt
99aaa9apaaoapaaaaaaqqqqqqqqqqqqqqqqbbbbbbbbbbbbbrrbbrrrrbrrbrrsrsrsrsssssssssrsssssssssssssssssssddddddddddddddtdtdtsttttttttttt
a9aaaapapooppaaaaaaaqqqqqqqqqqqqqqqqbqqbbbbbbbbbbbbbbrbbrbsrsrrsssrsssssssssssssssssssssssssssssssddddsdddddddddtdddtttttttttttt
aaaaaaappopppaaaaaaaaaqqqqqqqqqqqqqbqbbqbbqbbbbbbbbbbbbsbsbsrsssssssssssssssssssssssssssssssssssssssdsdsdsddddddddddtdtttttttttt
aa9aaaopppppppappaaaaaaqqqqqqqqqqqqqbqqbbqbbbbbbbbbcccscsssrsssssssssssssssssssssssssssssssssssssssssssdssdddddddddddttdttdttttt
aaaaaaapppppppppaaaaaaqqqqqqqqqqqqqqqqqbqbbbbbbbbbcccccsssssssssssssssssssssssssssssssssssssssssssssssdsdddddddddddddddttdtdtttt
9aaaaapppppppppppaaaaaaqqqqqqqqqqqqqqqqqbbqbcbbbbbbcccccssscssssssssssssssssssssssssssssssssssssssssssdddddddddddddddddtdtdtddtt
aaaaapppppppppppapaaaaaqqqqqqqqqqqqqqqqqrqbcbcccbbbccccccsccsssssssssssssssssssssssssssssssssssssssssdsdsdddddddddddddddtdtdtttt
aaaapapppppppppppaaaaaqaqqqqqqqqrqqqrrqrqrqccccccccbcccccccscscssssssssssscsssssssssssssssssssssssssssdsdssddddsdddddddddtdttttt
aaaaaappppppppppppaaaaaqaqqqqqqrrrrrrrrrrqccccccccccccccccscscssssssssssssssssssssssssssssssssssssssssssssdsddsdddddsdddddtttttt
aaaaapapppppppppppapaaaaaqqqqrqrrrrrrrrrrrqrcccccccccccccccscscsssssscscssssssssssssssssssssssssssssssssssssssdddddddsddddttttdt
aaaapappppppppppppqaaaaaaqqrrqrrrrrrrrrrrqrrrrrcccccccccccccccscsssssscssssssssssssssssssssssssssssssssssssdssdsdsdddddddddtddtd
paaapppppppppppppqpqaabaaarrrrqrrqrrrrrqrrrrrrrrccccccccccccccccscssscssssssssssssssssssssssssssssssssssssdsddddsddddddddddddddd
ppaaappppqppppppppqbqbpbbbrrrarrrrrrrrrrqrrrrrrccccccccccccccccccssssssssssssssssssssssssssssssssssssssssssdsddddssddddddddsdddd
pppappppqpqqqpqqppqqbbbbbbbrrrrrrqrrrrrrrrrrrrcrcccccccccrccccccsccscsssscsssssssssssssssssssssssssssssssssssddddsdsdsdddddddsdd
ppppppppqqqqqqqqqqqqbbbbbbrrrrrrrrrrrrrrrrrrrrrcrrccccccrccccccccccccsssccssssssssssssssssssssssssssssssssssssddsdsdddsdddsddddd
qppppqpppqqqqqqqqqqqqbpbbbbrrrrrrrrrrrrrrrrrrrrrrccrccccccccccccccccccscsscsssssssssssssssssssssssssssssssssssssdssddddsdsdddddd
pqppqqqpqqqqqqqqqqqqqqqqbbbbbbrrrrrrrrrrrrrrrrrrrrrccccccccccccccccccccsccssssssssssssssssssssssssssssssssssssssssdddddssdsddsdd
qqqqqqqqqqqqqqqqqqqqqqqqqbbbbbbrrrrrrrrrrrrrrrrrrrrrrcccccccccccccccccscscssssssssssssssssssssssssssssssssssssssssddddsdesessdde
qqqqqqqqqqqqqqqqqqqqqqqqqbbbbbrrrrrrrrrrrrrrrrrrrrrrcrrccccccccccccccccscscssssssssssrsssssssssssssssssssssssssssssdssdeseeedded
qqqqqqqqqqqqqqqqqqqqqqqqbbbbbbbrrrrrrrrrrrrrrrrrrrrrrrcrccccccccccccccccrcscscssssssssssssssssscssssssssssssssssstsssseeeeeeddee
qqqqqqqqqqqqqqqqqqqqqqqqqbbbbbbbbrrrrrrrrrrrrrrrrrrrrrrcrccccccccccccccccccccssssssssssssssssssssssssssssssssssststsstteeteeeeee
qqqqqqqqqqqpqqqqqqqqqqqqqqbbbbbbbbrrrrrrrrrrrrrrrrrrrrrrcccccccccccccccccccccccsssssssssssccssssssssssssssssssttttstttteteeeeeee
qqqqqqqqqqqqqqqqqqqqqqqqqqbbbbbbbbrrrrrrrrrrrrrrrrrrrrrrrrcccccccccccccccccccccccsssssssssscssssssssssssststsstttttttstteeteeeee
qqqqqqqqqqqqqqqqqqqqqqqqqbbbbbbbbbrrrrrrrrrrrrrrrrrrrrrrrrrcrcccccccccccccccccccsccssssssscssssssssssssststtttsttstttttteteeteee
qqqqqqqqqqqqqqqqqqqqqqqqqqbbbbbbbrbrbrrrrrrrrrrrrrrrrrrrrrcrcrcccccccccccccccccscsccssssssscsssstsstssststtttstctttttttttettetee
qqqqqqqqqqqqqqqqqqqqqqqqqqqbbbbbbbrbrrrrrrrrrrrrrrrrrrrrrrrcrcccccccccccccccccccsccsssscssssssststtstststtttcsctttttttttttttttet
qqqqqqqqqqqqqqqqqqqqqqqqqqqqbbbbbbbbbbrrrrrrrrrrrrrrrrrrrrrrrcrcccccccccccccccccccrssscstssssttstttttttttttsttttttttttttttttttte
qqqqqqqqqqqqqqqqqqqqqqqqqqqqbqbbbbbbbrrrrrrrrrrrrrrrrrrrrrrrrrccrcrccccccrrcccdcccdcsdstctsstttttstttttttttttttttttttttttttttttt
qqqqqqqqqqqqqqqqqqqqqqqqqqqqqbbbbbbbrrrrrrrrrrrrrrrrrrrrrrrrrrrrcrcrrccccccrcdcdcdcddcddtctttttttttttttttttttttttttttttttttttttt
qqqqqqqqqqqqqqqqqqqqqqqqqqqqqbqbqbbbbrrrbrrrrrrrrrrrrrrrrrrrrrrrrrrrcccccrrccdddcddccddtddtttdtttttttttttttttttttttttttttttttttt
qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqbqbbbbbrbrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrccdrrccdddddcdcddtdtdttttdttttttttttttttttttttttttttttttttt
qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqbbbbbbbrrbrrrrrrrrrrrrrrrrrrrrrrrrrrrrsdrcdrdcdddddcddddtcddttdtdtttdtttttttttttttttttttttttttttt
qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqbbbbbbbbrrrrrrrrrrrrrrrrrrrrrsrsrsrrssssdrddddddddddddddddtdttdtttttdttttttttttttttttttttttttttt
aqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqbbbbbbbrrrrrrrrrrrrrrrrrrrrsrsssssssssrrddddddddddddddddddddtddtttttdtttttdttttttttttttuttttttt
qaqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqbbbbbbbrrrrrrrrrrrsrrrsrrsssssssssssssssddddddddddddddddddddddddttttttttttttttttttttttutututtut
aqqqqqqqqqqqqaqqqqqqqqqqqqqqqqqqqbbbbbbbbrrbrrrrsrsrsssrssssssssssssssssssddddddddddddddddddddddddttttttttttttttttututtuuuuuuuuu
aaqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqbqbbbbbbbrrrssrssssssssssssssssrsssssssssssddddsddddddddddddddddtttttttttttttutututuututuuuuuu
aaqqqqqqqqqqqqqqqaqqqqqqqqqqqqqqqqqbbbbbbbbsssssssssssssssssssssssrssssssssssddddddddddddddddddddddtttutdtuutuutututuuuuuutuuuuu
aaaqqqqqqqqqqqqqqqaaqqqqqqqqqqqqqqqqqbbbbbscsssssssssssssssssssssssssssssssssdddddddddddddddddddddddtututuuuuuuutuuuuuuuuuuutuuu
aaqqqqqqqqqqqqqqaqaqqqqqqqqqqqqqrqqqrbbbbbcscssssssssssssssssssssssssssssssssdddsddddddsdddddddddddddeutdduuuuuuduuuuuuuuuuuuuuu
aaaqqqqqqqqqqqaaqaaaaqqqqqrqqqqrqrqrqrbbcbbcscssssssrsssssssssssssssssssssssssdsssdddddddedddddedeededuuudduuuuuuuuuuuuuuuuuuuuu
aaaaqqqqqqqqqaaaaaaaaaqqqrqrqqqqrrqqrrcccccccscsssssssssssssssssssssssssssssssssssssddddedesddedeeeeduuuuuuuduuuuuuuutuuuuuuuuuu
aaaaqqqqqqqqaaaaaaaaaaaqqqrqrrrrrrrrrcrccccccccssssssssssssssssssssssssssssssssssssssdeddeddeeseeeededuuuuduuueuuuuuuuuuuuuuuuuu
paaqaqqqqqqqqaaaabbabbbqqrrrrrrrrrrrrrccccccccsssssscssssssssssssssssssssssssstssssssesesdsedeeeeesedededeudeuuueuuuuuuuuuuuuuuu
ppaaaqqqqqqqaqaabbbbbbbbqrrrrrrrrrrrrrcccccccccsssscssssssssssssssssssssssstststsssstteesseeeeeeeeedeeeeedeeuuuuuuuuuuuuuuuuuuuu
paaaaqqqqrqqqbaabbbabbbbrbrrrrrrrrrrrrrccrccccccsssssssssssssssssssssssssstttttststttteseeeeeeeeeeeeeeeeeeeeeuuuuuuuuuuuuuuuuuuu
ppaaqqqqrqrqbbbbbbbbbbbbbrbrrrqrrrrrrrrrrccccccccsssssssssssssssssssssssssttttttttttttseeteeeeeeeeeeeeeeeeeeuuuuuuuuuuuuuuuuuuuu
ppaabqqqrrrbbbbbbbbbbbbbbbrrrqrrqrrrrrrrrrcccccqccccssssssssssstssssssstsstttttttttttststeteeeeeeteeeeeeeeeeeuuuuueuuuuuuuuuuuuu
pqbbabqrrrbbbbbbbbbbbbbbbbbrrrrrrrrrrrrrrrrcccccqccccssssssssstststsstttttsttttttttttttttttteeeeeeteeeeeeeeeeeeuuuueuuuuuuuuvuuu
qbbbbabqrbbbbbbbbbbbbbbbbbrrrrrrrrrrrrrrrrrcccccccccccsssststtstststtttttttttttttttttttttttteteeteeeeeeeeeeeeeeuuueuuuuuuuuvuvuu
qqbbabbbbbbbbbbbbbbbbbbbbbbbrrrrrrrrrrrrrrrrccccccccccctststtttststttttttttsttttttttttttttttteeteeeeeeeeeeeeeeeuuuueuuuuuuuvvuuv
pqqbbbbbrbbbbbbbbbbbbbbbbbbbbrrrrrrrrrrrrrrrrrccccdccctctttttttttttsttttttttttttttttttttttttttteteeeeeeeeeeeeeeeueeueeeeuvvvvvvu
qqbqbbbbbabbbbbbbbbbbbbbbbbbbbrrrrrrrrrrrrrrrrrcrdcddccttttttttttttttttttttttttttttttttttttttttteteeeeeteteeefeeeeeeeevvvvvvvvvv
qqqbbbbbabbbbbbbbbbbbbbbbbbbbbbrrrrrrrrsrrrrsscrdcddcddtdtdtttttttttsttttttttttttttttttttttttttttteeeetetefffefeffeeevvvvvvvvvvv
qqqbbbabbbbbbbbbbbbbbbbbbbbbbbbbrrrrrrsrssrssssdrddcddddddtdtttttttttttttttttttttttttttttttttttttttfteeteffffffffffeevvvvvvvvvvv
qqqbbbbbbbbbbbbbbbbbbbbbbbbbbbbrbrrrrssssrssssssddddddddcddcttttttttttttttttttttttttttttttttttttttftfetefeffffffffffvfvfvvvvvvvv
qqqqbbbbbbbbbbbbbbbbqqqbbbbbbbcbrsrsssssssrssssdddddddddddctdttdtcttttttttttttttttttttttttuutttttuufttefeffffffffffffvvvvvvfvvfv
qqqqqqabbbbbbbbbbbqqqqqqbcbbbcbcsrssssssssssssssddddddddddddttttdttttttttttttttttttttttttuuuutttuuuuuuueffuffffefffffvfvevfvfvvv
qqqqqbbbbbbbbbbbbbqqqrqrccccbccbbsssssssssssssssssrddddddddddttttttttttttttttttttttttuttuuuuuutuuuuuuuuuuuffffffffffffvfvfvfvfvv
qqqqqqbbbbbbbbbbrbqqrrrqrccccccccsssssssssrsssssssddddddddddddtttttttdttttttttttttttututuuuuuuututuuuuuufufffffffffffffffffvvvvv
qqqqqbbbbbbbbbcrqrrrrrrrqccccccccbsssssssssssssssssddddddddddddtttttttttttttttttttuututuuuuuuuuuuuuuuuufufffffffffutfffffffvfvvv
qqqqqqqcbbbbbcbcrrrrrrqrrbccccccccssssssssssssssssssddddddddddddddtttttttttttttttutuutuuuuuuuuuuuuuuuuuufuuffuffffuuufffffffvvfv
qqqqqrcqcbbbcbcrrrrrrrrrqrbcccccccsssssssssssssssssdsdddddddddddddttuttttuuttuuutuutuuuuuuuuuuuuuuuuuuutuuuuuuffffffffffffffffvf
qqrqrqrccbbcbccrrqrqrrrrrrrqccccccccssssssssssssssssdsdddddddddddeduuutduuuuuuuuuututuuuuuuuuututuuuuuuuuuuuuuufffffffffffffffff
qrrrrrqrcccbccbrqrrrrrrrrrrrcrcccccccsssssssssssssssssdddededdddedeuuuduuuuutuuuuuutuuuuuuuuuuuuuuuuuuuuuuuuuuuuffffffffffffffff
qrrrqrrcrccccrrrrrrrrrrrrrrrrccccccccscssssssssssssssssdedededdedeeuuduuuuuuututuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuufffffffffffffffff
brrrrqqrrcccrcrrrrrrrrrrrrrrrrccccccccsssssssssssssssssstededdedeeeeeueuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuufuffffffffffffffff
brrrrqrrrrcccrrrqrrrrrrrqrrrrcrccccccccssssssstsssssststttddedeeeeeeeeeeuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuufufffffffffffffff
bbrrrrqrrrcrrrrrrrrrrrrrrrrrrrccccccccssssssststtssststttteeeeseeeeeeeeeeuuuuuuuuuutuuuuuuuuuuuuuuuuuuuuuuuuuuuuufffffffffffffff
bbbrrrrrrrrrrrrrrrrrrrrrrrrrrrcrrccccccsssssssttstttststtteeeeeeeeeeeeeeeeuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuffuffuffffffff
bbbrrrrrrrrrrrrrrrrrrrrrrrrrrrrrcrcccccdssstsststttttstttteeeeeeeeeeeeeeeeeeuuuueuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuufufffufu
bbbrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrddccdcdststtstttttttttttteteteeeeeeeeeeeeeuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuufufffffuf
bbbrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrddddcddccststtttttttttttttteteeeeeeeeeeeeeueuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuffffffff
bbrbrrrrrrrrrrrrrrrrrrrrrrrrsrrrsdsdcdddddtttststtttttttttttttteeeeeeeeeeeeeueuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuufffffff
bbbrrrrrrrrrrrrrrrrrrrrrrsrsssrrrsdscddddddtttttttttttttttttttttteeeeeeeeeeeeeeueuuueuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuufufffuf
bbbrrrrrrrrrrrrrrrrrrrrssssssssrssssddcdddttttttttttttttstttttttteeeeeeeeeeeeeeeuueuueuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuufufuff
bbbrrrrrrrrrrssrrrssrrsrssssssssssssdsdddddttttttttttttttstttttteeeeeeeeeeeeeeeeueueuuuuueuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuufufff
bbbbrrrrrrrrssssssssssssssssssssrssssddddddddtttttttttttttttttttteeeeeeeeeeeeeeueueuueuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuffff
bbbrbrrrsrrrssssssssrssssssssssssrssssddddddttttttttttttttttttttttteeeeeeeeeeeeeueeeeueuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuufff
bbcbrrrsrsssssssssssssssssssssssssrsssddddddtttdtttttttttttttttttttteeeeeeeeeeeeeeeeueueuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu
ccccbcrrssssssssssssrssssssssssssssssssddddddtddtttttttttttttttttttteteeeeeeeeeeeeeeeueueueuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuvf
cccccscrsssssssrssssssssssssssssssssssssddddddddttttttttttttttttttttteteeeeeeeeeeeeeeeueuuuueuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuvuv
ccccccsssssssssssssssssssssssssssssssssssdddddddtttttttttttttttttttttttteeeeeeeeeeeeeeeuuuuuueuuuuuuuuuuuuuuuuuuuuuuuuuuvuuvuvvu
ccccccsssssssssssssssssssssssssssssssssssddddddtdttttttttttttttttttttttteeeeeeeeeeeeeeeeeuuuuueuuuuuuuuuuuuuuuuuuuuuuuuvuvvuvuvu
cccccccsssssssssssssssssssssssssssssssssssddddddtdttttttttttttttttttttttteeeeeeeeeeeeeeeeeeuuuuuuuuuuuuuuuuuuuuuuuuuuuvuvvuvuvvv
ccrccccrsssssssssssssssssssssssssssssssssddddddddtdttttttttttttttttttttttteeeeeeeeeeeeeeeeeeuuueuuuuuvuvuuuuuuuuvuuvuuuvuvvvvvvv
rrrrrcccssssssssssssssssssssssssssssssssssddddddddttttttttttttttttttttttttteteeeeeeeeeeeeeeeeeeuuuuuvuvvvvuuuvuvuvvuvvuuvuvvvvvv
rrrrcrccssssssssssssssssssssssssssssssssssddddddddtttttttttttttttttttttttteteteeeeeeeeeeeeeeeeeuuuuuvvvvvuvuvvvvvvvvvvvvvvvvvvvv
rrrcrcccssssssssssssssssssssssssssssssssssssdddddddtttttttttttttttttttttttteteteeeeteeeeeeeeeeueuvuvvvvvuvuvvvvuvvvvvvuvvvvvvvvv
rrrrccccsssssssssssssssssssssssssssssssssssdssdddddtdttttttttttttttttttttttteteeeeeeeeeeeeffeeeuvevvvvvvvvvvvvvvvvvvvuvvvvvvvvvv
rrrrrcccsssssssssssssssssssssssssssssssssssssdsdddddtdttttttttttttttttttttttteeeeeeeeeefefffffefevevvvvvvvvvvvvvvvvvvvvvvvvvvvvv
rrrrcrcccsssssssssssssssssssssssssssssssssssssddddddddttttttttttttttttttttttttteeeeeeefefffffefeffvvfvvvvvvvvvvvvvvvvvvvvvvvvvvv
rrrrrcccccssssssssssssssssssssssssssssssssssssdsdddddtdtttttttttttttttttttttttuteeeeefefeeffffefffffvvvvvvvvvvvvvvvvvvvvvvvvvvvv
rrrrrcrcccsssssssssssssssssssssssssssssssssssssdsdddddtdttttttttttttttttttttuututtffffffffffffffffffvvvvfvvvfvvvvvvvvvvvvvvvvvvv
rrrrrrcrscsssssssssssssssssssssssssssssssssssssssddddddtdtttttttttttttuttttutuutuuufffuffffffffffffffvvfvvvvvvvvvvvvvvvvvvvvvvvv
rrrrrrrcccssssssssssssssccsssssssssssssssssssssssdddddddtdtttttttttttututuuuuuuuuuufufufefffffffffffffffvvvvvvvvvvvvvvvvvvvvvvvv
rrrrrrrccscsssssssssssscccccssccsssssssssssssssssddddddddttttututtttuuuutuuuuuutuuutfuutfefffffffffffffffvvvvvvvvvvvvvvvvvvvoovv
rrrrrrccccscsssssssssssccccccccccsssssssssssssssdddddddddedtuuutuutuuuuuuuuuuutttuuututfufufffffffffffffffvfvvvvvvfvvvvvvvvoooov
rrrrrrrrcccsssssssssssscccccccccsssssssssssssssssddsddeeeeeuuuuuutuuuuuuuuuuutuuuuuuutuufufufffffffffffffffvfvvvvvvfvvvovvvvoooo
rrrrrrrrrcccsssssssssscscccccccccsssssssssssssstsssdeedeeeuduuuutuuuuuuuuuuuuuuuuuuuuuuuuuuftfffffffffffffffvfvvvvvovoovoovooooo
rrrrrrrrcccscsssssssssscccccccccccsssssssssssststssedeeddddueuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuufufffffffffffffffvfvooooovooovovooov
rrrrrrrrccccsssssssssccccccccccccccssssssstsssstsssteseeeddeeeuuuuuuuuuuuuuuuuuuuuuuuuuuuuufufffffffffff8fffffvo8ooooovovooovooo
rrrrrrrrrccccsssssssccccccccccccccccdsssststststtttsteeeeeeeeeeuuuuuuuuuuuuuuuuuuuuuuuuuuuuufffffffffff8f8f8f8o8o8ooooovoooooooo
rrrrrrrrcrccccsssssscccccccccccccdcdcdsssstttsttttttdteeeeeeeeuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuufffff8ffff88f8f8f8o8oooooooooo8oooo
rrrrrrrrrcrccccsssssccccccccccccdcdcdststststttttttsteteeeeeeeeuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuffff8f8fu8f88f8f8ff88oo8o8ooooo8ooo

